
DROP TABLE IF EXISTS user_transactions CASCADE;
DROP TABLE IF EXISTS master_transaction_types CASCADE;

CREATE TABLE user_payments (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    invoice_number VARCHAR(50) NOT NULL UNIQUE,
    user_id INT NOT NULL,
    service_id SMALLINT NOT NULL,
    amount INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_payment FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_service_payment FOREIGN KEY (service_id) REFERENCES master_services(id) ON DELETE CASCADE
);

CREATE TABLE user_topups (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    invoice_number VARCHAR(50) NOT NULL UNIQUE,
    user_id INT NOT NULL,
    amount INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_topup FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE invoice_daily_sequences (
    sequence_date DATE PRIMARY KEY,
    last_sequence INT NOT NULL DEFAULT 0
);

CREATE VIEW v_transaction_history AS (
    SELECT
        up.invoice_number,
        'PAYMENT' AS transaction_type,

        ms.service_name AS description,

        up.amount AS total_amount,

        up.created_at AS created_on,
        up.user_id
    FROM
        user_payments up
    JOIN
        master_services ms ON up.service_id = ms.id

    UNION ALL
    SELECT
        ut.invoice_number,
        'TOPUP' AS transaction_type,
        'Top Up balance' AS description,
        ut.amount AS total_amount,
        ut.created_at AS created_on,
        ut.user_id
    FROM
        user_topups ut
);